# Configuration file for the UDF-based preprocessing workflow

# Spark parameters
spark:
  driver:
    memory: 4
  executor:
    cores: 20
    memory: 20
  config:
    spark.driver.memory: "4g"

# JSONL Files to process
source:
  base: 's3a://polyglot-romance/'
  elem:
    - 'es/2_clean/*.jsonl'

# Destination prefix
dest: 's3a://polyglot-romance/'

# Preprocessing modules to use
preprocessing:

  seed: 1234

  # Language filter
  langfilter:
    chunk_size: 40
    lang:
      - es
      - fr
      - pt
      - it
      - ro

